# Generated by Django 6.0.5 on 2026-05-18 05:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_closed', models.BooleanField(default=False)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='deals.investorrequest')),
            ],
            options={
                'verbose_name': 'محادثة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسالة',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PitchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الجلسة')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='المدة (دقيقة)')),
                ('meeting_link', models.URLField(blank=True, verbose_name='رابط الاجتماع')),
                ('agenda', models.TextField(blank=True, verbose_name='جدول الأعمال')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'مطلوبة'), ('scheduled', 'مُجدولة'), ('done', 'مكتملة'), ('cancelled', 'مُلغاة')], default='requested', max_length=20)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_sessions', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_sessions', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'جلسة Pitch',
                'verbose_name_plural': 'جلسات Pitch',
                'ordering': ['-scheduled_at', '-requested_at'],
            },
        ),
    ]
