# Generated by Django 6.0.5 on 2026-05-19 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('profiles', '0004_startupprofile_burn_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=50, verbose_name='الخدمة المطلوبة')),
                ('service_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الخدمة')),
                ('payment_status', models.CharField(choices=[('unpaid', 'لم يُدفع'), ('paid', 'مدفوع')], default='unpaid', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_closed', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_conversations', to='profiles.advisorprofile')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محادثة مع مستشار',
                'unique_together': {('investor', 'advisor', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='AdvisorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.advisorconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
