# Generated by Django 4.2.30 on 2026-05-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advisory', '0001_initial'),
        ('profiles', '0004_startupprofile_burn_rate_and_more'),
        ('messaging', '0002_advisorconversation_advisormessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupAdvisorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('unpaid', 'لم يُدفع'), ('paid', 'مدفوع')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_closed', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_conversations', to='profiles.advisorprofile')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='advisory.servicerequest')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_conversations', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'محادثة شركة ↔ مستشار',
                'unique_together': {('startup', 'advisor')},
            },
        ),
        migrations.AlterModelOptions(
            name='advisorconversation',
            options={'verbose_name': 'محادثة مع مستشار (مستثمر)'},
        ),
        migrations.AddField(
            model_name='advisormessage',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='advisormessage',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='محجوبة'),
        ),
        migrations.AddField(
            model_name='message',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='سبب الحجب'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='محجوبة (بيانات حساسة)'),
        ),
        migrations.CreateModel(
            name='StartupAdvisorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False, verbose_name='محجوبة')),
                ('blocked_reason', models.CharField(blank=True, max_length=300)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.startupadvisorconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_advisor_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedDataRoomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='messaging.conversation')),
                ('dr_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_in_chats', to='data_room.dataroomfile')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_dr_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف مشارك',
                'verbose_name_plural': 'ملفات مشاركة',
                'ordering': ['-shared_at'],
            },
        ),
    ]
