# Generated by Django 6.0.5 on 2026-05-18 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=5, help_text='1 إلى 5')),
                ('review', models.TextField(blank=True, verbose_name='تعليق')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='profiles.advisorprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advisory.servicerequest')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'تقييم مستشار',
                'verbose_name_plural': 'تقييمات المستشارين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_strength', models.PositiveSmallIntegerField(default=5, help_text='0-10')),
                ('business_model', models.PositiveSmallIntegerField(default=5)),
                ('market_size', models.PositiveSmallIntegerField(default=5)),
                ('revenues', models.PositiveSmallIntegerField(default=5)),
                ('legal_readiness', models.PositiveSmallIntegerField(default=5)),
                ('tech_product', models.PositiveSmallIntegerField(default=5)),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_detail', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'نقاط شركة',
                'verbose_name_plural': 'نقاط الشركات',
            },
        ),
    ]
