# Generated by Django 6.0.5 on 2026-05-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupscore',
            name='business_model',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startupscore',
            name='legal_readiness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startupscore',
            name='market_size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startupscore',
            name='revenues',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startupscore',
            name='team_strength',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-10'),
        ),
        migrations.AlterField(
            model_name='startupscore',
            name='tech_product',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
