# Generated by Django 6.0.5 on 2026-05-18 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='المكان / رابط Zoom')),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True, verbose_name='محضر الاجتماع')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_meetings', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'اجتماع مجلس إدارة',
                'verbose_name_plural': 'اجتماعات مجلس الإدارة',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='MRR')),
                ('arr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ARR')),
                ('cac', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CAC')),
                ('ltv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='LTV')),
                ('churn_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Churn %')),
                ('notes', models.TextField(blank=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'KPI Snapshot',
                'verbose_name_plural': 'KPI Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('period', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربعي'), ('yearly', 'سنوي')], default='quarterly', max_length=20)),
                ('summary', models.TextField(verbose_name='ملخص تنفيذي')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الإيرادات')),
                ('burn_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Burn Rate')),
                ('runway_months', models.PositiveSmallIntegerField(default=0, verbose_name='Runway (شهور)')),
                ('customers_count', models.PositiveIntegerField(default=0, verbose_name='عدد العملاء')),
                ('team_size', models.PositiveSmallIntegerField(default=0)),
                ('achievements', models.TextField(blank=True, verbose_name='الإنجازات')),
                ('challenges', models.TextField(blank=True, verbose_name='التحديات')),
                ('file', models.FileField(blank=True, null=True, upload_to='ir/reports/', verbose_name='ملف التقرير (PDF)')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_reports', to='profiles.startupprofile')),
            ],
            options={
                'verbose_name': 'تقرير دوري',
                'verbose_name_plural': 'التقارير الدورية',
                'ordering': ['-sent_at'],
            },
        ),
    ]
